### ISSUE TITLE
Замечания       Cvesti     /     Lab-2

### ISSUE THREAD

**Issue by ananasn** [Cvesti/Lab-2#1]
1. Определяйте константы заглавными буквами. Так принято по [PEP8](https://peps.python.org/pep-0008/#constants). Располагайте их вверху после блока импортов.
2. В библиографических ссылках не указывайте время 
```19. Зайцева Анна Анатольевна. Вязание на лумах для начинающих. Просто, быстро, красиво. Техника, узоры, изделия - 24.04.2018 11:32```

**Comment by Cvesti** [comment]
Исправлено
